version: 2

jobs:
  checkout-code:
    docker:
      - image: circleci/ruby:2.4-node
    working_directory: ~/resultados-digitais
    branches:
      only:
        - master
    steps:
      - checkout
      - save_cache:
        key: rd-repo-{{ .Environment.CIRCLE_SHA1 }}
        paths:
          - ~/resultados-digitais
  
  bundle-denpendencies:
    working_directory: ~/resultados-digitais  
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - restore_cache:
          key: rd-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys: rd-bundle-{{ checksum "Gemfile.lock" }}
      run: bundle install --path vendor/bundle
      - save_cache:
          key: rd-bundle-{{ checksum "Gemfile.lock" }}
        paths:
          - ~/resultados-digitais/vendor/bundle

  test:
    working_directory: ~/resultados-digitais
    docker:
      - image: circleci/ruby:latest-browsers
    steps:
      - restore_cache:
          key: rd-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: rd-bundle-{{ checksum "Gemfile.lock" }}
      - run: bundle --path vendor/bundle
      - run: 
          name: Run cucumber tests
          command: bundle exec cucumber --tag 'not @wip' --format junit --out ~/cucumber/junit.xml
      - store_test_results:
          path: ~/cucumber/junit.xml

workflows:
  version: 2
  nightl:
    triggers:
      - schedule:
        cron: "0 0 * * *"
  build-and-test:
    jobs:
      - checkout-code
      - bundle-denpendencies
          requires: 
            - checkout-code
      - test:
          requires:
            - bundle-denpendencies