version: 2
jobs:
  checkout_code:
    working_directory: ~/resultados-digitais
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout
      -save_cache:
        key: rd-repo-{{ .Environment.CIRCLE_SHA1 }}
        paths:
          ~/resultados-digitais
  
  bundle_denpendencies:
    working_directory: ~/resultados-digitais  
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - restore_cache:
          key: rd-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: rd-bundle-{{ checksum "Gemfile.lock" }}
      run: bundle install --path vendor/bundle
      - save_cache:
          key: rd-bundle-{{ checksum "Gemfile.lock" }}
        paths:
          - ~/resultados-digitais/vendor/bundle

  test:
    working_directory: ~/resultados-digitais
    docker:
      - image: circleci/ruby:latest-browsers
    steps:
      - restore_cache:
          key: rd-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: rd-bundle-{{ checksum "Gemfile.lock" }}
      - run: bundle --path vendor/bundle
      - run: bundle exec cucumber --tag 'not @wip' --format junit --out ~/cucumber/junit.xml
      - store_test_results:
          path: ~/cucumber/junit.xml

workflows:
  version: 2
  build_and-test:
    jobs:
      - checkout_code
      - bundle_denpendencies
          requires: 
            - checkout_code
      - test:
          requires:
            - bundle_denpendencies