version: 2

jobs:
  checkout_code:
    docker:
      - image: circleci/ruby:2.4-node
    working_directory: ~/resultados-digitais
    steps:
      - checkout
      - save_cache:
          key: rd-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/resultados-digitais

  bundle_dependencies:
    working_directory: ~/resultados-digitais  
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - restore_cache:
          keys:
            - rd-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - rd-bundle-{{ checksum "Gemfile.lock" }}
      - run: 
          name: Bundle install
          command: bundle install --path vendor/bundle
      - save_cache:
          key: rd-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/resultados-digitais/vendor/bundle
  
  code_analyzer:
    working_directory: ~/resultados-digitais  
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - restore_cache:
          keys:
            - rd-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - rd-bundle-{{ checksum "Gemfile.lock" }}
      - run:
          name: Rubocop analyzer
          command: bundle exec rubocop

  test:
    working_directory: ~/resultados-digitais
    docker:
      - image: circleci/ruby:latest-browsers
    steps:
      - restore_cache:
          keys:
            - rd-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - rd-bundle-{{ checksum "Gemfile.lock" }}
      - run: 
          name: Bundle install
          command: bundle --path vendor/bundle
      - run: 
          name: Execute all features scenarios (except @wip tags)
          command: bundle exec cucumber --tag 'not @wip' --format junit --out ~/cucumber/junit.xml
      - store_test_results:
          path: ~/cucumber/junit.xml

workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout_code
      - bundle_dependencies:
          requires: 
            - checkout_code
      - code_analyzer:
          requires:
            - bundle_dependencies
      - test:
          requires:
            - bundle_dependencies