version: 2

jobs:
  checkout_code:
    docker:
      - image: circleci/ruby:2.4-node
    working_directory: ~/resultados-digitais
    steps:
      - checkout
      - save_cache:
          key: rd-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/resultados-digitais

  bundle_dependencies:
    working_directory: ~/resultados-digitais  
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - restore_cache:
          keys:
            - rd-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - rd-bundle-{{ .Branch }}
      - run: 
          name: Bundle install
          command: bundle install --path vendor/bundle
      - save_cache:
          key: rd-bundle-{{ .Branch }}-{{ epoch }}
          paths:
            - ~/resultados-digitais/vendor/bundle
      - save_cache:
          key: rd-bundle-{{ .Branch }}
          paths: 
            - ~/resultados-digitais/vendor/bundle
  
  code_analyzer:
    working_directory: ~/resultados-digitais  
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - restore_cache:
          keys:
            - rd-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - rd-bundle-{{ .Branch }}
      - run: 
          name: Bundle install
          command: bundle install --path vendor/bundle
      - run:
          name: Rubocop analyzer
          command: bundle exec rubocop

  chrome_test:
    working_directory: ~/resultados-digitais
    docker:
      - image: circleci/ruby:latest-browsers
    steps:
      - restore_cache:
          keys:
            - rd-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - rd-bundle-{{ .Branch }}
      - run: 
          name: Bundle install
          command: bundle install --path vendor/bundle
      - run: 
          name: Execute all features scenarios (except @wip tags) on Goole Chrome browser
          command: bundle exec cucumber --profile chrome --profile not_wip --profile ci
      - store_test_results:
          path: ~/report
      - store_artifacts:
          path: ~/report

  # firefox_test:
  #   working_directory: ~/resultados-digitais
  #   docker:
  #     - image: circleci/ruby:latest-browsers
  #   steps:
  #     - restore_cache:
  #         keys:
  #           - rd-repo-{{ .Environment.CIRCLE_SHA1 }}
  #     - restore_cache:
  #         keys:
  #           - rd-bundle-{{ .Branch }}
  #     - run: 
  #         name: Bundle install
  #         command: bundle install --path vendor/bundle
  #     - run: 
  #         name: Execute all features scenarios (except @wip tags) on Goole Chrome browser
  #         command: bundle exec cucumber --profile firefox --profile not_wip --profile ci
  #     - store_test_results:
  #         path: ~/cucumber/junit.xml

workflows:
  version: 2
  build_and_test:
    # triggers:
    #   - schedule:
    #       cron: "* 4 * * *"
    #       filters:
    #         branches:
    #           only: master
    jobs:
      - checkout_code
      - bundle_dependencies:
          requires: 
            - checkout_code
      - code_analyzer:
          requires:
            - bundle_dependencies
      - chrome_test:
          requires:
            - bundle_dependencies
            - code_analyzer
      # - firefox_test:
      #     requires:
      #       - bundle_dependencies
      #       - code_analyzer